/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Producto;
import Clases.Venta;
import Interfaces.Dao.IDaoProductos;
import Interfaces.Dao.IDaoVenta;
import dao.DaoProductoImpl;
import dao.DaoVentaImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juang
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        modelo.setColumnIdentifiers(new Object[]{"id","producto","cantidad","Precio Final"});
        CargarProd();
        //CargaTabla();
    }

    
    private void CargaTabla(){
         try{
             
            Producto p = new Producto();
            p = (Producto) jComboBox1.getSelectedItem();
            int precio = Integer.parseInt(jTextField1.getText()) * p.getPrecioNeto();
            
            modelo.addRow(new Object[]{
                p.getDBID_Producto()
                ,p.getNombre()
                ,jTextField1.getText()
                ,precio
            });

            jTable1.setModel(modelo);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Por favor Ingresa Numeros NO :"+jTextField1.getText());
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    private void CargarProd(){
        try{

            IDaoProductos Daopro = new DaoProductoImpl();

             List<Producto> lstPro = Daopro.Listar();
            for(int i=0; i <= lstPro.size(); i++){
                Producto pro = lstPro.get(i);
                System.out.println(pro);
                //jComboBox1.addItem(lstPro.get(i).getNombre());
                jComboBox1.addItem(pro);
                
            }
        }
        catch(Exception e){
            System.out.println(e);
        }


    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButtonHistorico = new javax.swing.JButton();
        jButtonAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonComprar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonHistorico.setText("Historial deventa");
        jButtonHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoricoActionPerformed(evt);
            }
        });

        jButtonAdmin.setText("Administrador");
        jButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenido al Minimarket Donde Juanito");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonComprar.setText("Comprar");
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Producto:");

        jLabel3.setText("Cantidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonHistorico)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAdmin))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAgregar)
                                    .addComponent(jButtonComprar))
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHistorico)
                    .addComponent(jButtonAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonComprar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminActionPerformed
        
        Administrador ad = new Administrador();
        this.dispose();
        ad.show();
        this.hide();
        
    }//GEN-LAST:event_jButtonAdminActionPerformed

    private void jButtonHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoricoActionPerformed
        HistoricoVentas HV = new HistoricoVentas();
        this.hide();
        HV.show();
    }//GEN-LAST:event_jButtonHistoricoActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // Agregar datos a ventas
        try{
            CargaTabla();
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed
        //registrar tabla1 a tabla ventas
        try{
            
        
            jTable1.getSelectedRow();
            IDaoVenta dv = new DaoVentaImpl();
            IDaoProductos dp = new DaoProductoImpl();
            List<Producto> lstP = new ArrayList();
            lstP = dp.Listar();
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                Venta venta = new Venta();
                Producto Producto = new Producto();
                System.out.println("Registro número: "+i);
                System.out.println("ID: "+jTable1.getValueAt(i, 0));
                System.out.println("NOMBRE: "+jTable1.getValueAt(i, 1));
                System.out.println("CANTIDAD: "+jTable1.getValueAt(i, 2));
                System.out.println("TOTAL: "+jTable1.getValueAt(i, 3));
                venta.setID_PRODUCTO(jTable1.getValueAt(i, 1).toString());
                venta.setCANTIDAD( Integer.parseInt(jTable1.getValueAt(i, 2).toString()));
                venta.setPRECIO_FINAL(Integer.parseInt( jTable1.getValueAt(i, 3).toString()));
                dv.Registrar(venta);
                int id = (int) jTable1.getValueAt(i, 0);
                for(int j=0;j < lstP.size() ;j++){
                    if(id == lstP.get(j).getDBID_Producto()){
                        int Resta = lstP.get(j).getCantidad() - Integer.parseInt(jTable1.getValueAt(i, 2).toString()) ;
                        if(Resta >= lstP.get(j).getCantidadMinima()){
                            lstP.get(j).setCantidad( Resta);
                            dp.Modificar(lstP.get(j));
                        }else if(Resta  <= lstP.get(j).getCantidadMinima() && Resta >= 0 ){
                            JOptionPane.showMessageDialog(null, "Se Necesita mas Stock Para el Producto: "+lstP.get(j).getNombre());
                            lstP.get(j).setCantidad( Resta);
                            dp.Modificar(lstP.get(j));
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Se Acabo el Stock Para el Producto: "+lstP.get(j).getNombre()+
                                    "Se vendieron: "+lstP.get(j).getCantidad());
                            lstP.get(j).setCantidad(0);
                            dp.Modificar(lstP.get(j));
                        }
                        //((DefaultTableModel)jTable1.getModel()).removeRow(i);
                    }
                }
                
                
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JButton jButtonHistorico;
    private javax.swing.JComboBox<Producto> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
